"""Telemetry package exposing metrics, tracers, and usage reporting."""

from .runtime import get_tracer, meter
from .metrics import (
    authz_decision_total,
    missing_policy_total,
    policy_poll_total,
    policy_poll_updated,
    policy_file_reload_total,
    policy_poll_clamped_total,
    policy_poll_stale_total,
    policy_load_latency_ms,
    jwks_fetch_latency_ms,
    jwks_rotation_total,
    local_tool_count,
    authz_decision_latency_ms,
    authz_denied_reason_total,
    tool_invocation_total,
    tool_exec_latency_ms,
    policy_poll_interval_seconds,
    policy_poll_failure_total,
    policy_bundle_age_seconds,
    context_leak_total,
    context_stale_total,
    sync_in_async_denied_total,
)
from .usage import UsageReporter

__all__ = [
    "UsageReporter",
    "authz_decision_total",
    "missing_policy_total",
    "policy_poll_total",
    "policy_poll_updated",
    "policy_file_reload_total",
    "policy_poll_clamped_total",
    "policy_poll_stale_total",
    "policy_load_latency_ms",
    "jwks_fetch_latency_ms",
    "jwks_rotation_total",
    "local_tool_count",
    "authz_decision_latency_ms",
    "authz_denied_reason_total",
    "tool_invocation_total",
    "tool_exec_latency_ms",
    "policy_poll_interval_seconds",
    "policy_poll_failure_total",
    "policy_bundle_age_seconds",
    "context_leak_total",
    "context_stale_total",
    "sync_in_async_denied_total",
    "get_tracer",
    "meter",
]
